name: publish

on:
  push

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        env:
          username: ${{ github.actor }}
          imagename: publishdocker
          version: 0.0.4
        run: |
            docker build . --tag ghcr.io/$username/$imagename:$version
            docker run ghcr.io/$username/$imagename:$version
            docker push ghcr.io/$username/$imagename:$version